### ISSUE TITLE
24-3.4.5 - variables in /etc/nginx/sites.available/nextcloud.conf are not expanded

### ISSUE THREAD

**Issue by joergmschulz** [tiredofit/docker-nextcloud#22]
the variables 
```server {
    listen {{NGINX_LISTEN_PORT}};
    root {{NGINX_WEBROOT}}; 
```
are not expanded. So nginx doesn't start but displays
`nginx: [emerg] directive "listen" is not terminated by ";" in /etc/nginx/sites.enabled/nextcloud.conf:2`

**Comment by tiredofit** [comment]
I just rebuilt the images one more time and don't see it on my end. Can you confirm?

**Comment by joergmschulz** [comment]
YES 
```server {
    listen 80;
    root /www/nextcloud;
```
all is working fine. Thank you again for all this work.
