### ISSUE TITLE
 PHP Warning:  Version warning: Imagick was compiled against ImageMagick version 1808 but version 1809 is loaded. 

### ISSUE THREAD

**Issue by joergmschulz** [tiredofit/docker-nextcloud#27]
using [26-latest](https://hub.docker.com/layers/tiredofit/nextcloud/26-latest/images/sha256-9f5ec308359aa978420283ed735614163f58cee5cbf2ffe876f731358486f00d?context=explore) 

startup throws a warning:  PHP Warning:  Version warning: Imagick was compiled against ImageMagick version 1808 but version 1809 is loaded. Imagick will run but may behave surprisingly in Unknown on line 0

**Comment by tiredofit** [comment]
Seeing it as well on my side. We're going to have to wait till Alpine:edge gets in sync. I have a notification set watching for any updtes.

Hasn't affected my ability to use theming in 26.

**Comment by joergmschulz** [comment]
Inded, looks good. Let's wait for the alpine sync / thank you for that brand new version and its included fixes.
