### ISSUE TITLE
Version 27.0.0 - do not use in production env

### ISSUE THREAD

**Issue by joergmschulz** [tiredofit/docker-nextcloud#29]
Following the github issues for NC 27: there are multiple issues, one prominent is that groupfolders and fulltextsearch cannot be used at the same time.
So: only use for testing and looking for just some more issues.... (will close this one when a significant number of issues disappeared)

**Comment by tiredofit** [comment]
Thanks! I have 27 running on a personal instance with lots of strange issues happening right now, but I am tolerant for it. My clients? Not so much. We're looking at only rolling out 26 in July and 27 after. The marketing for 27 pretty much rehashed the last 10 releases ..

**Comment by joergmschulz** [comment]
Indeed. 26 looks stable here. Including Collabora and bigbluebutton integration and fulltextsearch and calendar newsletter and snappymail.

**Comment by joergmschulz** [comment]
There is a new version of full text search. Now all seems to be running fine.
