### ISSUE TITLE
broken link in README.md

### ISSUE THREAD

**Issue by fuchsi3010** [tiredofit/docker-nextcloud#6]
hi,

the link https://github.com/tiredofit/docker-nextcloud/blob/master/examples/docker-compose.yml doesnt seem to work, even tough it's linked in the Readme.

Any way to get to those docker-compose files?

Thanks!

**Comment by tiredofit** [comment]
Yes, I just split the master branch into seperate branches yesterday.  Have a peek at 21, 22, 23. I will clean them up right now to support this new shift.

**Comment by fuchsi3010** [comment]
ahh! i see now. i tried going through the commit history but that didn't work obviously... 
TIL how to switch to branches on github.
thanks!
