### ISSUE TITLE
Dockerfile not present here

### ISSUE THREAD

**Issue by joergmschulz** [tiredofit/docker-nextcloud#7]
Just wanted to suggest the upgrade to 23.0.1 - but the Dockerfile is missing here ....

**Comment by tiredofit** [comment]
Hi sorry I split them back into seperate branches. For my production environments I'm typically running a major release behind now due to some stability issues and the fact that the plugin eco system is a mess. Have a peek at branch `23`.

**Comment by joergmschulz** [comment]
True - sorry I forgot that within 2 weeks after installing the 23 version. Created PR.
